packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': false
  argon2: true
  esbuild: false
  msgpackr-extract: false
  prisma: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - argon2
  - esbuild
  - prisma
  - '@tailwindcss/oxide'

verifyDepsBeforeRun: false
